import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { ArrowUpRight, DollarSign, Users, Wrench, Zap, Calendar } from "lucide-react"

export default function HostDashboardPage() {
  return (
    <>
      <div className="flex items-center">
        <h1 className="text-lg font-semibold md:text-2xl">Dashboard</h1>
        <div className="ml-auto flex items-center gap-2">
          <Button size="sm" variant="outline">
            <Calendar className="mr-2 h-4 w-4" />
            Last 30 Days
          </Button>
          <Button size="sm">Add Property</Button>
        </div>
      </div>

      {/* --- KPI METRICS ROW --- */}
      <div className="grid gap-4 md:grid-cols-2 md:gap-8 lg:grid-cols-4">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Total Revenue</CardTitle>
            <DollarSign className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">$12,450.00</div>
            <p className="text-xs text-muted-foreground">
              +18% from last month
            </p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Occupancy Rate</CardTitle>
            <Users className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">84%</div>
            <p className="text-xs text-muted-foreground">
              +4% above market avg
            </p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Active Listings</CardTitle>
            <Zap className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">3</div>
            <p className="text-xs text-muted-foreground">
              All systems nominal
            </p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Pending Tasks</CardTitle>
            <Wrench className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">2</div>
            <p className="text-xs text-muted-foreground">
              1 high priority
            </p>
          </CardContent>
        </Card>
      </div>

      {/* --- AI INTELLIGENCE SECTION --- */}
      <div className="grid gap-4 md:gap-8 lg:grid-cols-2 xl:grid-cols-3">
        
        {/* Predictive Maintenance Card */}
        <Card className="xl:col-span-2">
          <CardHeader className="flex flex-row items-center">
            <div className="grid gap-2">
              <CardTitle>AI Attention Needed</CardTitle>
              <CardDescription>
                Proactive alerts generated by our predictive engine.
              </CardDescription>
            </div>
            <Button asChild size="sm" className="ml-auto gap-1">
              <a href="#">
                View All
                <ArrowUpRight className="h-4 w-4" />
              </a>
            </Button>
          </CardHeader>
          <CardContent>
            <div className="grid gap-4">
              {/* Alert 1 */}
              <div className="flex items-center gap-4 rounded-lg border p-4 bg-amber-50 dark:bg-amber-900/20">
                <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-amber-600/20 text-amber-600">
                  <Wrench className="h-5 w-5" />
                </div>
                <div className="grid gap-1">
                  <div className="flex items-center gap-2">
                    <p className="text-sm font-medium leading-none">HVAC Anomaly Detected</p>
                    <Badge variant="outline" className="text-amber-600 border-amber-200">Downtown Loft</Badge>
                  </div>
                  <p className="text-sm text-muted-foreground">
                    Sensors detect irregular cycling patterns. 85% chance of failure within 2 weeks.
                  </p>
                </div>
                <Button size="sm" variant="secondary" className="ml-auto">
                  Schedule Tech
                </Button>
              </div>

              {/* Alert 2 */}
              <div className="flex items-center gap-4 rounded-lg border p-4 bg-blue-50 dark:bg-blue-900/20">
                <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-blue-600/20 text-blue-600">
                  <DollarSign className="h-5 w-5" />
                </div>
                <div className="grid gap-1">
                  <div className="flex items-center gap-2">
                    <p className="text-sm font-medium leading-none">Pricing Opportunity</p>
                    <Badge variant="outline" className="text-blue-600 border-blue-200">Seaside Villa</Badge>
                  </div>
                  <p className="text-sm text-muted-foreground">
                    "Tech Summit 2024" announced for next month. Recommend raising rates by 25%.
                  </p>
                </div>
                <Button size="sm" variant="secondary" className="ml-auto">
                  Apply Update
                </Button>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Recent Activity / Simple List */}
        <Card>
          <CardHeader>
            <CardTitle>Recent Activity</CardTitle>
          </CardHeader>
          <CardContent className="grid gap-8">
            <div className="flex items-center gap-4">
              <div className="grid gap-1">
                <p className="text-sm font-medium leading-none">
                  Booking Confirmed
                </p>
                <p className="text-sm text-muted-foreground">
                  Alex J. for "Downtown Loft"
                </p>
              </div>
              <div className="ml-auto font-medium text-green-600">+$450.00</div>
            </div>
            <div className="flex items-center gap-4">
              <div className="grid gap-1">
                <p className="text-sm font-medium leading-none">
                  Smart Lock Code Sent
                </p>
                <p className="text-sm text-muted-foreground">
                  Automated delivery to Guest
                </p>
              </div>
              <div className="ml-auto text-sm text-muted-foreground">2m ago</div>
            </div>
            <div className="flex items-center gap-4">
              <div className="grid gap-1">
                <p className="text-sm font-medium leading-none">
                  Review Received
                </p>
                <p className="text-sm text-muted-foreground">
                  5 stars from Sarah M.
                </p>
              </div>
              <div className="ml-auto text-sm text-muted-foreground">1h ago</div>
            </div>
             <div className="flex items-center gap-4">
              <div className="grid gap-1">
                <p className="text-sm font-medium leading-none">
                  Cleaning Scheduled
                </p>
                <p className="text-sm text-muted-foreground">
                  Vendor: Spotless Inc.
                </p>
              </div>
              <div className="ml-auto text-sm text-muted-foreground">5h ago</div>
            </div>
          </CardContent>
        </Card>
      </div>
    </>
  )
}